# 端口号
server:
  port: 8081

myYml:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
